#!/usr/bin/env bash

input_path=$1

if [ "$input_path" == "~" ]; then
    expanded_path="$HOME"
elif [[ $input_path == \~/* ]]; then
    expanded_path="${HOME}/${input_path:2}"
else
    expanded_path="$input_path"
fi

echo "$expanded_path"
