#!/bin/sh

if [ $# -ne 1 ]; then
    echo "needs 1 arg" 1>&2
fi

if [ "$1" -eq "$1" ]; then
    :
else
    echo "arg needs to be numeric" 1>&2
    exit 1
fi

grep -Fx -f <(hyprctl clients -j | jq '.[] .pid' | sort -nr) <(psancestors $1) | awk ' NR==1 '
