#!/bin/sh

if [ $# -ne 1 ]; then
    echo "needs 1 arg" 1>&2
fi

if [ "$1" -eq "$1" ]; then
    :
else
    echo "arg needs to be numeric" 1>&2
    exit 1
fi

pid=$1
pid=$(ps -p "$pid" -o ppid= | awk ' { print $1 } ')
if [ -z "$pid" ]; then
    echo "proc with id doesn't exist" 1>&2
    exit 1
fi
echo "$pid"
if [ "$pid" -eq 1 ]; then
    exit 0
fi
while :; do
    pid=$(ps -p "$pid" -o ppid= | awk ' { print $1 } ')
    echo "$pid"
    if [ "$pid" -eq 1 ]; then
        break
    fi
done
