#!/usr/bin/env bash

# Get the directory of the currently executing script
dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
dir+="/cfg"

if [[ $# -eq 1 ]]; then
    selected=$1
else
    # Read locations from floc.txt in the script's directory, expand tildes, and join them with spaces
    search_locations=""
    while IFS= read -r line; do
        search_locations+=" $(eval echo $line)"
    done < "$dir/wloc.txt"

    selected=$(find -L $search_locations -mindepth 1 -maxdepth 1 -type d 2> >(grep -v "Too many levels of symbolic links" >&2) | sort | uniq | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

# If inside a tmux session
if [[ ! -z $TMUX ]]; then
    if ! tmux has-session -t=$selected_name 2> /dev/null; then
        tmux new-session -ds $selected_name -c $selected
    fi
    tmux switch-client -t $selected_name
    exit 0
fi

# If outside a tmux session
if tmux has-session -t=$selected_name 2> /dev/null; then
    tmux attach -t $selected_name
else
    tmux new-session -s $selected_name -c $selected
fi

